### ISSUE TITLE
L-Event Calendar Rows Out of Line

### ISSUE THREAD

**Issue by jeremylturner88** [loitruong/l-events-calendar#13]
I am having issues with the L-Event plugin for WordPress.  The rows are not aligned correctly.  Has anyone had this issue before?

**Comment by loitruong** [comment]
Hi, I'm sorry for my late response. Can you please provide me screenshot or link (I would prefer link, since i believe my plugin has conflict with your css). Thank you.

**Comment by jeremylturner88** [comment]
You can view it here:

http://ssmcme.org/church-events/

Jeremy Turner

Founder/CEO

Teach Me Technology, LLC

 http://www.tmt4all.com/ www.tmt4all.com

 http://www.facebook.com/tmt4all  http://www.twitter.com/tmt4all  https://www.instagram.com/tmt4all/  https://www.youtube.com/channel/UCeBFubUWEmYgsdaq6u6tcfQ  https://plus.google.com/b/102007451894827829651/+TeachMeTechnologyTMTLLCLewisville/about?gmbpt=true&pageId=102007451894827829651&_ga=1.16443060.366710953.1461874668  https://www.linkedin.com/company/9552764?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A9552764%2Cidx%3A2-1-2%2CtarId%3A1461875859335%2Ctas%3Ateach%20me%20technology

**Comment by josephfusco** [comment]
@jeremylturner88 This is due to a box-sizing issue on the date boxes.
@loitruong I have submitted the pull request for review to fix this issue.

**Comment by josephfusco** [comment]
Hey @jeremylturner88 all set in [version 1.0.2](https://github.com/loitruong/l-events-calendar/archive/v1.0.2.zip)

You can manually install the plugin after downloading it here on GitHub. Hopefully we will get the wordpress.org version updated to this version too.

Thanks for bringing up the issue!
