### ISSUE TITLE
Move LEC Settings menu link from main sidebar to L Events submenu

### ISSUE THREAD

**Issue by josephfusco** [loitruong/l-events-calendar#7]
## Move up as submenu

<img width="334" alt="screen shot 2015-09-02 at 9 57 13 pm" src="https://cloud.githubusercontent.com/assets/6676674/9649101/27f8a17e-51be-11e5-90ae-61ee3b652bae.png">
## Now the whole plugin is self contained

<img width="669" alt="screen shot 2015-09-02 at 9 58 26 pm" src="https://cloud.githubusercontent.com/assets/6676674/9649103/2b5d3546-51be-11e5-8acc-59d9b7dd6570.png">

**Comment by loitruong** [comment]
wow awesome idea, good job sir

**Comment by josephfusco** [comment]
fyi i never did that, just used dev tools to show how it should look :smile:
